jwt:
  secret: sdfhjkgvbsdlfgbvsdfhjlvgbljasdgflasdfg
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop

  login:
    level:
      org:
        hibernate:
          SQL:DEBUG
